version: "3"

networks:
  grutec: {}

services:
  database:
    networks:
    - grutec
    volumes:
    - .:/app/db
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: appdb
    image: postgres:11.2-alpine

  application:
    depends_on:
    - database
    networks:
    - grutec
    volumes:
    - .:/app
    ports:
    - "5000:5000"
    build:
      context: "."
      dockerfile: Dockerfile